;;;;;;;;;;;;;;;;;;;;;;
; Dynamic PHP Extensions Enabled for osTicket & LDAPS ;
;;;;;;;;;;;;;;;;;;;;;;
extension=curl
extension=fileinfo
extension=gd
extension=intl
extension=ldap
extension=openssl
;extension=opcache
extension=mbstring
extension=mysqli
